"""PyInstaller entry point for the dokey executable.

The console script generated by pip cannot be frozen directly; this file is
the equivalent doorway. ``freeze_support`` keeps any multiprocessing child a
library spawns from re-running the whole CLI.
"""
import multiprocessing

from dokey.cli import main

if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()
